name: Build & Release study_swiper CLI

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_suffix: linux-x86_64
            ext: ''
            package_cmd: |
              tar -C dist -czf study_swiper-linux-x86_64.tar.gz study_swiper
          - os: windows-latest
            artifact_suffix: windows-x86_64
            ext: '.exe'
            package_cmd: |
              powershell Compress-Archive -Path dist\\study_swiper.exe -DestinationPath study_swiper-windows-x86_64.zip
          - os: macos-12
            artifact_suffix: macos-x86_64
            ext: ''
            package_cmd: |
              tar -C dist -czf study_swiper-macos-x86_64.tar.gz study_swiper
          - os: macos-14
            artifact_suffix: macos-arm64
            ext: ''
            package_cmd: |
              tar -C dist -czf study_swiper-macos-arm64.tar.gz study_swiper
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller flit_core

      - name: Create PyInstaller entry script
        run: |
          cat << 'EOF' > run_study_swiper.py
          from study_swiper import cli

          if __name__ == '__main__':
              cli()
          EOF

      - name: Build standalone executable
        run: |
          pyinstaller \
            --onefile \
            --name study_swiper${{ matrix.ext }} \
            run_study_swiper.py

      - name: Package executable
        run: ${{ matrix.package_cmd }}

      - name: Upload compiled artifact
        uses: actions/upload-artifact@v4
        with:
          name: study_swiper-${{ matrix.artifact_suffix }}
          path: |
            *.tar.gz
            *.zip

  release:
    name: Draft GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create / update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: study_swiper ${{ github.ref_name }}
          generate_release_notes: true
          files: dist/**/*.*
